### ISSUE TITLE
db is not defined

### ISSUE THREAD

**Issue by DBMfan** [disbotlist-xyz/DisBotlist#5]
Hello, I am getting this error when I try to add my server to my own list.
```
(node:286) UnhandledPromiseRejectionWarning: ReferenceError: db is not defined
at /app/src/server.js:149:22
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/4401a8d8-8e34-426e-8bd9-0435d984cd70/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/4401a8d8-8e34-426e-8bd9-0435d984cd70/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
at global.checkAuth (/app/src/server.js:97:41)
```

How can I fix this?

**Comment by appujet** [comment]
const db in server .js

**Comment by appujet** [comment]
Close
